blank_issues_enabled: false
contact_links:
  - name: Vault Manager
    url: https://github.com/Dick-s-Vault/vault-manager/issues
    about: Please report organization-wide issues or automation bugs here.
